image: eve-wwan 
org: lfedge
network: yes
config:
  binds:
    - /lib/modules:/lib/modules
    - /dev:/dev
    - /run:/run
  net: host
  capabilities:
    - all
  devices:
    - path: all
      type: a
