FROM lfedge/eve-rhel:9ad685cd8abb440ce4c7101bf5f0a828f3a525dd-dirty-aa26ab2 as tools
#ENV PKGS qemu-img tar u-boot-tools coreutils dosfstools
ENV PKGS qemu-img tar coreutils dosfstools
RUN eve-rhel-deploy.sh

# hadolint ignore=DL3006
FROM MKISO_TAG as iso
# hadolint ignore=DL3006
FROM IPXE_TAG as ipxe
# hadolint ignore=DL3006
FROM MKRAW_TAG as raw
# we need to get rid of embedded initrd & installer.img since we will get them from outside
RUN rm /initrd.img /installer.img
# hadolint ignore=DL3006
FROM MKCONF_TAG as conf

COPY --from=iso / /
COPY --from=raw / /
COPY --from=ipxe / /
COPY --from=tools /out/ /
COPY installer /bits
COPY runme.sh /
RUN mkdir /in /out


# These labels indicate where each component type is.
# These must be updated if we change filenames or locations.
# The annotations to be used are available at https://github.com/lf-edge/edge-containers/blob/master/docs/annotations.md
LABEL org.lfedge.eci.artifact.root="/bits/rootfs.img"
LABEL org.lfedge.eci.artifact.initrd="/bits/initrd.img"

WORKDIR /bits
ENTRYPOINT ["/runme.sh"]
