image: eve-wlan
org: lfedge
network: yes
config:
  binds:
    - /lib/modules:/lib/modules
    - /lib/firmware:/lib/firmware
    - /dev:/dev
    - /run:/run
    - /config:/config
  net: host
  capabilities:
    - all
  devices:
    - path: all
      type: a
