#!/bin/sh
ifconfig "$1" 0.0.0.0 up
#** SuSE nor RHEL do not provide `brctl`
#** from opendev "Replace deprecated brctl with ip commands"
#** brctl addif "$2" "$1" || true
ip link set dev "$1" master "$2" || true
